# Generated by Django 6.0.4 on 2026-04-28 18:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_refreshtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'access_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='refreshtoken',
            new_name='refresh_tok_token_h_2fa7c6_idx',
            old_name='refresh_tok_token_ha_3c7e5f_idx',
        ),
        migrations.RenameIndex(
            model_name='refreshtoken',
            new_name='refresh_tok_expires_a128d9_idx',
            old_name='refresh_tok_expires__8a9f3c_idx',
        ),
        migrations.RenameIndex(
            model_name='refreshtoken',
            new_name='refresh_tok_revoked_3e6e61_idx',
            old_name='refresh_tok_revoked_2b8d4a_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_deleted_e48316_idx',
            old_name='users_delet_bf8c39_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_email_4b85f2_idx',
            old_name='users_email_1d9e06_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_phone_af6883_idx',
            old_name='users_phone_a3da76_idx',
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='users.user'),
        ),
        migrations.AddIndex(
            model_name='accesstoken',
            index=models.Index(fields=['token_hash'], name='access_toke_token_h_149d92_idx'),
        ),
        migrations.AddIndex(
            model_name='accesstoken',
            index=models.Index(fields=['expires_at'], name='access_toke_expires_c63347_idx'),
        ),
        migrations.AddIndex(
            model_name='accesstoken',
            index=models.Index(fields=['revoked'], name='access_toke_revoked_d812a4_idx'),
        ),
    ]
