# Generated by Django 6.0.3 on 2026-03-28 09:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('type', models.CharField(default='character', max_length=50)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('class_name', models.CharField(blank=True, max_length=50)),
                ('ancestry', models.CharField(blank=True, max_length=50)),
                ('heritage', models.CharField(blank=True, max_length=100)),
                ('background', models.CharField(blank=True, max_length=100)),
                ('hp_max', models.PositiveSmallIntegerField(default=15)),
                ('hp_current', models.PositiveSmallIntegerField(default=15)),
                ('speed', models.PositiveSmallIntegerField(default=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'characters',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['deleted_at'], name='characters_deleted_d88d09_idx'), models.Index(fields=['name'], name='characters_name_e3e6c1_idx')],
            },
        ),
    ]
